### PR TITLE
Typo: changed newDesciptionBuilder to newDescriptionBuilder

### PR DESCRIPTION
**Pull request by chaquotay**
Typo: changed newDesciptionBuilder to newDescriptionBuilder

### CODE REVIEW

**Comment by ddekany** [comment]
Thanks!

**Comment by chaquotay** [comment]
No problem. I had this one lurking around in my eternal todo list for more than three years and finally managed to create a PR :-)

**Comment by ddekany** [comment]
Good to see your around again by the way! If you feel like hacking some FM (including the (going-to-be-)much sexier FM3), or any related side projects (like the new Eclipse plugin in the making), don't resist! ;)

**Comment by chaquotay** [comment]
Working with Java again might be fun. Especially the IDE/LSP stuff sounds interesting :-)

**Comment by ddekany** [comment]
So, if you want to discuss this or anything further, let's move from this PR comment section to the FM dev mailing list, or to my mail personal mail!

**Pull request merged**
